version: '3'
services:
    web:
      build: .
      ports:
        - 3003:3003
      environment:
        API_URL: ${API_URL:-http://localhost:5000}
      logging: 
        driver: "json-file"
        options:
          max-size: "50mb"


    mongo:
      image: mongo
      restart: always
      # DB Ports not exposed by default.
      # ports:
      #   - 27017:27017
      volumes:
        - mongoData:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSOWORD:-P@ssw00rd!}
      networks:
        - backend
      logging:
        driver: "json-file"
        options:
          max-size: "50mb"


    backend:
      image: testing-webapp-server
      restart: always
      build:
        context: ./server
        dockerfile: ./Dockerfile
      command: dev
      expose:
        - "5000"
      environment:
        MONGO_USERNAME: ${MONGO_USERNAME:-root}
        MONGO_PASSOWORD: ${MONGO_PASSOWORD:-P@ssw00rd!}
        MONGO_HOST: ${MONGO_HOST:-mongo}
        MONGO_PORT: ${MONGO_PORT:-27017}
        MONGO_DATABASE: ${MONGO_DATABASE:-test_execution_result}
        PORT: ${BACKEND_PORT:-5000}
      depends_on:
        - mongo
      networks:
        - backend
        - default
      logging:
        driver: "json-file"
        options:
          max-size: "50mb"


networks:
  backend:

volumes:
  mongoData:
