services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/nginx/acme:/etc/acme.sh
    environment:
      NGINX_PROXY_CONTAINER: 'nginx'

  web:
    image: ghcr.io/govstackworkinggroup/testing-webapp/frontend:latest
    build:
      args:
        API_URL: https://api.staging.testing.govstack.global
    environment:
      VIRTUAL_HOST: staging.testing.govstack.global
      LETSENCRYPT_HOST: staging.testing.govstack.global
      API_URL: api.staging.testing.govstack.global

  backend:
    image: ghcr.io/govstackworkinggroup/testing-webapp/backend:latest
    command: yarn prod
    volumes:
      - /var/docker/uploads:/app/uploads
    environment:
      VIRTUAL_HOST: api.staging.testing.govstack.global
      LETSENCRYPT_HOST: api.staging.testing.govstack.global

  mongo:
    ports:
      - 27017:27017
