version: '3'
services:
  web:
    volumes:
      - .:/testing-webapp/frontend
      - ./testing-webapp/frontend/node_modules
    ports:
      - 3003:3003

  backend:
    volumes:
      - ./backend:/app
      - ./app/node_modules

