version: '3'
services:
    web:
      build: .
      ports:
        - 89:3003

    mongo:
      image: mongo
      restart: always
      # DB Ports not exposed by default.
      ports:
        - 29017:27017
      volumes:
        - mongoData:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSOWORD:-P@ssw00rd!}
      networks:
        - backend

    backend:
      image: testing-webapp-server
      restart: always
      build:
        context: ./server
        dockerfile: ./Dockerfile
      command: dev
      ports:
        - 5000:5000
      environment:
        MONGO_USERNAME: ${MONGO_USERNAME:-root}
        MONGO_PASSOWORD: ${MONGO_PASSOWORD:-P@ssw00rd!}
        MONGO_HOST: ${MONGO_HOST:-mongo}
        MONGO_PORT: ${MONGO_PORT:-27017}
        MONGO_DATABASE: ${MONGO_DATABASE:-test_execution_result}
        API_KEY_BB: ${API_KEY_BB:-asudbq827ebsadon}
        PORT: ${BACKEND_PORT:-5000}
      depends_on:
        - mongo
      networks:
        - backend

networks:
  backend:

volumes:
  mongoData:
