services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker/nginx/acme:/etc/acme.sh
    environment:
      NGINX_PROXY_CONTAINER: 'nginx'

  web:
    image: ghcr.io/govstackworkinggroup/testing-webapp/frontend:latest
    build:
      args:
        API_URL: ${API_URL}
    environment:
      VIRTUAL_HOST: ${FRONTEND_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${FRONTEND_LETSENCRYPT_HOST}

  backend:
    image: ghcr.io/govstackworkinggroup/testing-webapp/backend:latest
    command: yarn prod
    volumes:
      - /var/docker/uploads:/app/uploads
    environment:
      EMAIL_SENDER: ${EMAIL_SENDER}

      ENABLE_JIRA_INTEGRATION: ${ENABLE_JIRA_INTEGRATION}

      GITBOOK_API_KEY: ${GITBOOK_API_KEY}
      GITBOOK_ORG_ID: ${GITBOOK_ORG_ID}
      GITBOOK_URL: ${GITBOOK_URL}

      GITHUB_CALLBACK_URL: ${GITHUB_CALLBACK_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_JWT_SECRET: ${GITHUB_JWT_SECRET}
      GITHUB_ORGANIZATION: ${GITHUB_ORGANIZATION}
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
      GITHUB_REVIEWRS_TEAM: ${GITHUB_REVIEWRS_TEAM}

      JIRA_API_DOMAIN: ${JIRA_API_DOMAIN}
      JIRA_API_ENDPOINT: ${JIRA_API_ENDPOINT}
      JIRA_API_KEY: ${JIRA_API_KEY}
      JIRA_ASSIGNEE_ID: ${JIRA_ASSIGNEE_ID}
      JIRA_DESCRIPTION_TEMPLATE: ${JIRA_DESCRIPTION_TEMPLATE}
      JIRA_ISSUE_TYPE: ${JIRA_ISSUE_TYPE}
      JIRA_LABELS: ${JIRA_LABELS}
      JIRA_PROJECT_KEY: ${JIRA_PROJECT_KEY}
      JIRA_TITLE_TEMPLATE: ${JIRA_TITLE_TEMPLATE}
      JIRA_USER_EMAIL: ${JIRA_USER_EMAIL}

      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}

      SEND_FORM_CONFIRMATION_EMAILS: ${SEND_FORM_CONFIRMATION_EMAILS}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}

      VIRTUAL_HOST: ${BACKEND_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${BACKEND_LETSENCRYPT_HOST}
