version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_test:
    executor: 
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Lint the codebase
      - run:
          command: yarn test
          name: Run YARN tests

  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d1:b2:46:4e:a2:e8:3b:10:0b:49:78:06:fa:92:25:52"
            # Add your new test server's SSH fingerprint here
            - "staging fingerpring"
      - run:
          command: cp ./ssh-config ~/.ssh/config
          name: Setup SSH Config
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan prod-server >> ~/.ssh/known_hosts
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              ssh-keyscan staging-server >> ~/.ssh/known_hosts
            fi
          name: Add known host for SSH
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash deployment/deploy.sh prod
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              bash deployment/deploy.sh staging
            fi
          name: Deploy based on branch

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
           requires:
             - build_and_test
           filters:
             branches:
               only:
                 - master
                 - development
