version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_test:
    executor: 
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Lint the codebase
      - run:
          command: yarn test
          name: Run YARN tests
  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d1:b2:46:4e:a2:e8:3b:10:0b:49:78:06:fa:92:25:52"
      - run:
          command: echo 'testing.govstack.global ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1G9AC3OysP3RMhfHMmLp++aEEcE+K3k3EGm16OexnG' >> ~/.ssh/known_hosts
          name: Add known host for SSH
      - run:
          command: bash deployment/deploy.sh
          name: Deploy to test server

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
           requires:
             - build_and_test
           filters:
             branches:
               only:
                 - main

