version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.3

jobs:
  build_and_test:
    executor: 
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Lint the codebase
      - run:
          command: yarn test
          name: Run YARN tests
  deploy:
    steps:
      - run:
          command: bash deployment/deploy.sh
          name: Deploy to test server

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
           requires:
             - test
           filters:
             branches:
               only:
                 - main

